-- 008_et_penalty_support.sql
ALTER TABLE fixtures
  ADD COLUMN IF NOT EXISTS et_home INT NULL,
  ADD COLUMN IF NOT EXISTS et_away INT NULL,
  ADD COLUMN IF NOT EXISTS pen_home INT NULL,
  ADD COLUMN IF NOT EXISTS pen_away INT NULL,
  ADD COLUMN IF NOT EXISTS phase TEXT NULL; -- 'FT'|'AET'|'PEN'
